/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Timer_Main.h"
#include "Timer_Duration.h"
#include "isr_NextSample.h"
#include "isr_StopSamples.h"
#include "IDAC_1.h"
#include "WaveOutput.h"
#include "WaveOutput_aliases.h"
#include "Start_Button_Board.h"
#include "Start_Button_Board_aliases.h"
#include "isr_Start.h"
#include "Start_Button_External.h"
#include "Start_Button_External_aliases.h"
#include "isr_Start_1.h"
#include "Green_Led_Start.h"
#include "Green_Led_Start_aliases.h"
#include "Green_Led_Start_Board.h"
#include "Green_Led_Start_Board_aliases.h"
#include "Mode_1_LED.h"
#include "Mode_1_LED_aliases.h"
#include "Mode_2_LED.h"
#include "Mode_2_LED_aliases.h"
#include "Mode_1_Button.h"
#include "Mode_1_Button_aliases.h"
#include "isr_Mode_1.h"
#include "Mode_2_Button.h"
#include "Mode_2_Button_aliases.h"
#include "isr_Mode_2.h"
#include "LCD_Char_1.h"
#include "LCD_Char_1_LCDPort.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

