# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\HP\Documents\PSoC Creator\Turchyn_TR-41z_KR.cydsn\Turchyn_TR-41z_KR.cyprj
# Date: Sat, 06 Apr 2024 13:05:11 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for C:\Users\HP\Documents\PSoC Creator\Turchyn_TR-41z_KR.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\HP\Documents\PSoC Creator\Turchyn_TR-41z_KR.cydsn\Turchyn_TR-41z_KR.cyprj
# Date: Sat, 06 Apr 2024 13:05:08 GMT
